### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by RalphMichel** [znerol/python-dgst-concat#3]
I had the following error message after running the script: 
`UnicCodeDecodeError: 'utf-8' codec can't decode byte 0x92 inposition 43: invalid start byte. `
My solution was to add `errors='ignore'` behind decode in the file "lib.py" in line 97. The script worked afterwards but I'm not sure if this has other effects on the script or if it would be a good idea to add `errors='ignore'` by default.

`97     chunk = buf.peek().decode(errors = 'ignore')`

**Comment by znerol** [comment]
Thank you for the report. The problem seems to be that `buf.peek()` potentially returns an incomplete `utf-8` string. So your suggestion is very likely correct.

**Comment by znerol** [comment]
Pushed your fix and released v1.3.1. Thanks again for the report and the fix.
